GET http://localhost:3000/posts
Authorization: Bearerey
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4ODQ1OTkyOH0.Enc6lhRV6PnbKXRpIzQcg_0fF6Kl2osuLasw3gEo6kY

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Kyle"
}